### ISSUE TITLE
Broken HTTPS when viewing admin config

### ISSUE THREAD

**Issue by dave-swift** [agnostack/magento_extension#61]
Extension stuffs a Zendesk logo at the top of the admin configuration page in the Magento admin.  However, the image is served from a Zendesk server, not the Magento system.  The URL to the logo is hardcoded to use HTTP, but (hopefully) all Magento admin run over a secure connection.

The URL is at https://github.com/zendesk/magento_extension/blob/master/src/skin/adminhtml/default/default/zendesk/zendesk.css#L37

``` css
h3.zendesk-header {
    background: url(http://cdn.zendesk.com/images/zendesk-logo.png) no-repeat scroll 0 0 transparent;
    height: 65px;
    overflow: hidden;
    padding: 0;
    text-indent: -9999px;
    width: 200px;
}
```

Ideally, the image should be served locally.  Suggested fix would be to add the image to the skin directory and change the line code to:

``` css
h3.zendesk-header {
    background: url(zendesk-logo.png) no-repeat scroll 0 0 transparent;
    height: 65px;
    overflow: hidden;
    padding: 0;
    text-indent: -9999px;
    width: 200px;
}
```
